import { vue } from 'vue';
import {
    AutoComplete,
    Button,
    Menu,
    Icon,
    Table,
    Tabs,
    Select,
    Radio,
    InputNumber,
    Input,
    Spin,
    DatePicker,
    Modal,
    Pagination,
    Tag,
    Divider,
    ConfigProvider,
    Form,
    FormModel,
    Breadcrumb,
    Checkbox,
    Tooltip,
    Card,
    Row,
    Col,
    Switch,
    Upload,
    Tree,
    Progress,
    Calendar,
    Dropdown,
    List,
    Descriptions,
    Cascader,
    Popconfirm,
    Steps,
    Result,
    Layout,
    TreeSelect
} from "ant-design-vue";
import 'ant-design-vue/dist/antd.less';

//第三方库
Vue.use(AutoComplete);
Vue.use(Button);
Vue.use(Menu);
Vue.use(Icon);
Vue.use(Table);
Vue.use(Tabs);
Vue.use(Select);
Vue.use(Radio);
Vue.use(InputNumber);
Vue.use(Input);
Vue.use(Spin);
Vue.use(DatePicker);
Vue.use(Modal);
Vue.use(Pagination);
Vue.use(Tag);
Vue.use(Divider);
Vue.use(ConfigProvider);
Vue.use(Form);
Vue.use(FormModel);
Vue.use(Breadcrumb);
Vue.use(Checkbox);
Vue.use(Tooltip);
Vue.use(Card);
Vue.use(Row);
Vue.use(Col);
Vue.use(Switch);
Vue.use(Upload);
Vue.use(Tree);
Vue.use(Progress);
Vue.use(Calendar);
Vue.use(Dropdown);
Vue.use(List);
Vue.use(Descriptions);
Vue.use(Cascader);
Vue.use(Popconfirm);
Vue.use(Steps);
Vue.use(Result);
Vue.use(Layout);
Vue.use(TreeSelect);
